server:
  port: 8081

spring:
  application:
    name: ms-neb-student
  # Data source settings
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-uni?currentSchema=public
    username: miguelcarb
    password: miguelcarbpost890
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000